# Generated by Django 4.2.7 on 2023-11-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vidyo_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="watermark_image",
            field=models.ImageField(blank=True, null=True, upload_to="watermarks/"),
        ),
        migrations.AddField(
            model_name="video",
            name="watermark_position",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
