# Generated by Django 4.2.7 on 2023-11-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vidyo_processing", "0003_video_processed_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="processed_time",),
    ]
