# Generated by Django 4.2.7 on 2023-11-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vidyo_processing", "0004_remove_video_processed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="original_video_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="processed_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="video",
            name="processed_video_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="processing_type",
            field=models.CharField(default="default_value", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="watermark_position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
